import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-[#f4edc9] text-gray-900">
        <div className="sticky top-0 z-50 bg-[#f4edc9] shadow-[0_2px_10px_rgba(0,0,0,0.08)]">
          <header className="bg-[#f4edc9] border-b border-gray-300">
            {/* Row 1 */}
            <div className="relative max-w-7xl mx-auto px-4 py-6">
              {/* Top slogans */}
              <div className="absolute left-4 top-2 text-[#1f3b6d] font-medium font-semibold">
                வாழ்க வையகம்
              </div>
              <div className="absolute right-4 top-2 text-[#1f3b6d] font-medium font-semibold">
                வாழ்க வளமுடன்
              </div>

              {/* Center text (true center) */}
              <div className="absolute inset-0 flex flex-col items-center justify-center text-center pointer-events-none">
                <h1 className="font-extrabold text-[#0f6b3a] text-xl md:text-xl whitespace-nowrap">
                  குரு வேதாத்திரி மகரிஷி அவர்களின் அருளாசியுடன்
                </h1>

                <h2 className="font-extrabold text-[#1f3b6d] text-base md:text-lg mt-1 whitespace-nowrap">
                  குரோம்பேட்டை ராதா நகர் மனவளக்கலை மன்றம் அறக்கட்டளை
                </h2>

                <p className="text-sm mt-1 text-[#1f3b6d]">
                  7, ஏழுமலை தெரு, ராதா நகர், குரோம்பேட்டை, சென்னை – 600 044.
                </p>
                <p className="mt-2 text-[#1e40af] text-sm md:text-base flex justify-center gap-6 flex-wrap">
                  <span>📞 9884374090, 9962206217</span>
                  <span>✉️ skychrompet@yahoo.com</span>
                </p>
              </div>

              {/* Logos */}
              <div className="flex justify-between items-center px-6 md:px-12">
                <img
                  src="/logo-wcsc.png"
                  alt="WCSC SKY"
                  className="h-[56px] md:h-[100px] w-auto"
                />
                <img
                  src="/logo-skyyoga.png"
                  alt="SKY Yoga"
                  className="h-[56px] md:h-[120px] w-auto"
                />
              </div>
            </div>

            {/* Row 2 – Menu */}
            <div className="bg-[#f4edc9] border-t ">
              <div className="max-w-7xl mx-auto px-4 py-2 flex justify-center gap-8 ">
                <a
                  href="/learn"
                  className="hover:underline text-[#1f3b6d] hover:text-[#b08a2e] font-semibold"
                >
                  பயிற்சிகள்
                </a>
                <a
                  href="/learn"
                  className="hover:underline text-[#1f3b6d] hover:text-[#b08a2e] font-semibold"
                >
                  தியானம் செய்முறை
                </a>
                <a
                  href="/events"
                  className="hover:underline text-[#1f3b6d] hover:text-[#b08a2e] font-semibold"
                >
                  நிகழ்வுகள்
                </a>
              </div>
            </div>
            <div className="h-[2px] w-full bg-gradient-to-r from-transparent via-[#d4b16a] to-transparent" />
          </header>
        </div>

        <main className="flex-1">{children}</main>

        <footer className="bg-[#0b3b5c] text-white text-center py-3 text-xs">
          © 2026 ராதா நகர் SKY யோக மன்றம் இது அதிகாரப்பூர்வ இணையதளம் அல்ல. தகவல்
          சேவைக்காக மட்டுமே.
        </footer>
      </body>
    </html>
  );
}
